### ISSUE TITLE
Instagram switch not working

### ISSUE THREAD

**Issue by cpfotiadis** [claromes/socialswitch#7]
Hello,

For TikTok there is no problem, the switch works normally either to UrleBird or to Xaller. 
For Instagram however no switch works for me.

When I have Picuki selected it takes me here: https://www.picuki.com/profile/accounts

When I have Imginn selected it takes me here: https://imginn.com/accounts/

**Comment by claromes** [comment]
Hi. The issue isn't very clear. But in some cases, the redirection will only go to one of the web viewers, regardless of which one you select. This is made explicit in the "Supported URLs" link in the popup.

**Comment by claromes** [comment]
Hi, @cpfotiadis . After some testing with Mullvad, I discovered the issue. The extension works in some locations, but in others, the error you reported occurs. The problem is that the VPN service redirects profile URLs to a new login URL, which I hadn't parsed. Well, this weekend I'll adjust the parsing and update the extension by next week. I'll let you know here when the solution is implemented. Thank you for opening the issue.

**Comment by cpfotiadis** [comment]
I'm glad I helped by reporting the problem. I will wait for the new update, because I definitely like your extension and I want to use it at the same time as I use the VPN.

**Comment by claromes** [comment]
@cpfotiadis Bug fixed. The new version has already been sent to the Chrome Web Store and should be available in 1 day, but if you prefer, you can install it manually. Thank you.

**Comment by cpfotiadis** [comment]
I received the update normally from the Chrome Web Store. Now it seems to work perfectly, I didn't see any problems. Good job @claromes and thank you very much!
